#pragma once
#define WIN_WIDTH 640
#define WIN_HEIGHT 480
#define COLOR_BIT_DEPTH 32

#define TILE_SIZE 60
#define PLAYER_WIDTH 60
#define PLAYER_HEIGHT 50

#define SCROLL_SPEED 6

#define PLAYER_SPEED 10
#define PLAYER_JUMP_POWER 40
#define PLAYER_JUMP_TIME 30
#define GRAVITY 15

#define SCORE_TIME 1
#define SCORE_ITEM 500

#define TIME_LIMIT 180